language: perl

install:
  - cpanm -n --installdeps .
  # for t/inline*.t tests
  - ./maint/min-perl.pl 5.010 cpanm -n Inline::C Inline::CPP

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

script:
  # basic test without anything optional installed
  - perl Build.PL
  - ./Build
  - ./Build test verbose=1

sudo: false
